### ISSUE TITLE
Example with existing xib Views

### ISSUE THREAD

**Issue by Glideh** [Dromaguirre/DRPageScrollView#2]
It would be great to have an example paginating on existing Views from xib files.
I naively imagine something like:

```objective-c
self.pages = @[
   (UIView *)[[[NSBundle mainBundle] loadNibNamed:@"MyView1"] lastObject],
   (UIView *)[[[NSBundle mainBundle] loadNibNamed:@"MyView2"] lastObject],
];

for (UIView *page in self.pages) {
    [self.paginatedScrollView addPageWithHandler:^(UIView *pageView) {
        [pageView addSubview: page];
    }];
}
```

**Comment by lewis-smith** [comment]
+1 for this, it would be good to have some storyboard examples. For me this doesn't work at all. If I get something going I'll post back here.

**Comment by Dromaguirre** [comment]
I'm extremely sorry for being absent for so long. I'm really busy with high school so I haven't been able to take care of these issues.

Recently I started to work on a major update for this library, providing some new features and an overall cleaning of the code. I'll take this request into account and include a xib example when I release the new version.

I'd be more than pleased to provide you with that example now, but I'm about to do final exams and university access tests so my time is really limited for me right now. I hope you can understand.

**Comment by hsavit1** [comment]
High school ??

**Comment by Dromaguirre** [comment]
A brand-new version is now up and ready to be used. I've made sure to include a nib/xib example implementation. Enjoy! :tada:

**Comment by Dromaguirre** [comment]
@hsavit1 yup, last year. I've been pretty busy, but it's getting easier now.

**Comment by hsavit1** [comment]
That's fantastic mate. Best of luck to you I'm sure you have a bright career ahead of you!
