### ISSUE TITLE
MASLayoutPriorityRequired error

### ISSUE THREAD

**Issue by 99centsappdevelopment** [Dromaguirre/DRPageScrollView#5]
I am having an error (I think with the podfile), whereby I am getting the following error  in MASUtilities.h, line 16-20:
Use of undeclared identified "MASLayoutPriority..." and Expression is not an integer constant expression. Any idea why this is happening?

**Comment by Dromaguirre** [comment]
Sorry about this, I shouldn't have made a demo app using CocoaPods in the first place. A major update will be released in the following days. Please stay tuned and sorry for the super late answer, I've been crazy busy with school.

**Comment by Dromaguirre** [comment]
@99centsappdevelopment a completely new version is now up. It doesn't require Masonry anymore or any other CocoaPod, so problem solved :tada:
