### ISSUE TITLE
Not work on iOS 7, but why?

### ISSUE THREAD

**Issue by world000** [Dromaguirre/DRPageScrollView#6]
Excellent work. but it does not work on iOS 7, and its pods deployment is iOS 8 indeed. but why? No API is available from iOS 8.

**Comment by Dromaguirre** [comment]
You're absolutely right. I'll change that.

**Comment by Dromaguirre** [comment]
There seems to be a few bugs causing an incorrect behavior of this library on iOS 7, specially size and constraint bugs. I don't think I'll have time to fix those, even less now with iOS 9 right around the corner. If you want to find out those bugs for yourself, fix them and send me a pull request, I'll be totally happy to merge it.
